# Blueprint: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: sominnercore
    runtime: docker
    plan: free
    branch: landingpage-feature
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
